# version: "3.0"
# services:
#   # my-nestjs-app:
#   #   container_name: nestjs-app
#   #   # Other configuration for your NestJS app container
#   #   ports:
#   #     - 3000:3000
#   #   networks:
#   #     - es-net
#   elasticsearch:
#     container_name: es-container
#     image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
#     environment:
#       - xpack.security.enabled=false
#       - "discovery.type=single-node"
#     networks:
#       - es-net
#     ports:
#       - 9200:9200
#   kibana:
#     container_name: kb-container
#     image: docker.elastic.co/kibana/kibana:8.13.0
#     environment:
#       - ELASTICSEARCH_HOSTS=http://es-container:9200
#     networks:
#       - es-net
#     depends_on:
#       - elasticsearch
#     ports:
#       - 5601:5601
# networks:
#   es-net:
#     driver: bridge

version: '3'

services:
  service-auth:
    build:
      context: ./ServiceAuth
    ports:
      - "3001:3001"
    env_file:
      - path: ./.env 
        required: true
    depends_on:
      - mongodb
      - redis

  gateway:
    build:
      context: ./Microservice
    ports:
      - "3000:3000"
    networks:
      - app-network
    env_file:
      - path: ./.env 
        required: true
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: datn@2024
      MONGO_INITDB_DATABASE: nest
    ports:
      - "27017:27017"

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

networks:
  app-network:
    driver: bridge