name: Deploy to VPS

on:
  push:
    branches:
      - main  # Change to your specific branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Set up SSH
      env:
        VPS_IP: ${{ vars.VPS_IP }}
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ env.VPS_IP }} >> ~/.ssh/known_hosts

    - name: Copy files to VPS
      env:
        VPS_IP: ${{ vars.VPS_IP }}
        DEST_PATH: ${{ vars.PATH }}
      run: |
        sshpass -e scp -o StrictHostKeyChecking=no -r . admin@${{ env.VPS_IP }}:${{ env.DEST_PATH }}

    - name: Deploy on VPS
      env:
        VPS_IP: ${{ vars.VPS_IP }}
        PROJECT_PATH: ${{ vars.PROJECT_PATH }}
      run: |
        sshpass -e ssh -o StrictHostKeyChecking=no admin@${{ env.VPS_IP }} "cd ${{ env.PROJECT_PATH }} && docker-compose up -d --build"