name: Deploy to VPS

on:
  push:
    branches:
      - main  # Change to your specific branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Set up SSH
      env:
        SSHPASS: ${{ secrets.SSH_PASSPHRASE }}
      run: |
        eval "$(ssh-agent -s)"
        ssh-add <(echo "$SSHPASS" | sshpass -P "Enter passphrase for " ssh-add <(echo "${{ secrets.SSH_PRIVATE_KEY }}"))

    - name: Copy files to VPS
      run: scp -r -o StrictHostKeyChecking=no . admin@${{ vars.VPS_IP }}:${{ vars.PATH }}

    - name: Deploy on VPS
      run: ssh -o StrictHostKeyChecking=no admin@${{ vars.VPS_IP }} 'cd ${{ vars.PROJECT_PATH }} docker-compose up -d --build'
